spring:
  application:
    name: spring-batch-tutorial
  batch:
    job:
      enabled: false

server:
  port: 8080

payroll:
  import:
    csv-path: classpath:sample-data/timesheets-import-sample.csv
    chunk-size: 100
    skip-limit: 50
